CREATE TABLE heap_table(
    id integer,
    name varchar
);

CREATE TABLE part_hub_table (
    id integer,
    name varchar
) PARTITION BY HASH (id);

CREATE TABLE part_1
PARTITION OF part_hub_table
FOR VALUES WITH (MODULUS 10, REMAINDER 0);

CREATE TABLE part_2
PARTITION OF part_hub_table
FOR VALUES WITH (MODULUS 10, REMAINDER 1);

CREATE TABLE part_3
PARTITION OF part_hub_table
FOR VALUES WITH (MODULUS 10, REMAINDER 2);

CREATE TABLE part_4
PARTITION OF part_hub_table
FOR VALUES WITH (MODULUS 10, REMAINDER 3);

CREATE TABLE part_5
PARTITION OF part_hub_table
FOR VALUES WITH (MODULUS 10, REMAINDER 4);

CREATE TABLE part_6
PARTITION OF part_hub_table
FOR VALUES WITH (MODULUS 10, REMAINDER 5);

CREATE TABLE part_7
PARTITION OF part_hub_table
FOR VALUES WITH (MODULUS 10, REMAINDER 6);

CREATE TABLE part_8
PARTITION OF part_hub_table
FOR VALUES WITH (MODULUS 10, REMAINDER 7);

CREATE TABLE part_9
PARTITION OF part_hub_table
FOR VALUES WITH (MODULUS 10, REMAINDER 8);

CREATE TABLE part_10
PARTITION OF part_hub_table
FOR VALUES WITH (MODULUS 10, REMAINDER 9);